### ISSUE TITLE
question: Error when configuring

### ISSUE THREAD

**Issue by kiliankoe** [JDevlieghere/InTeXration#3]
Unfortunately I'm a complete noob when it comes to Python.. The prerequisites are all there, but when I try to run `python3 -m intexration -host localhost -port 8000` I get this output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./intexration/__main__.py", line 2, in <module>
    from intexration.intexration import Intexration
  File "./intexration/intexration.py", line 5, in <module>
    from intexration.server import Server, RequestHandler
  File "./intexration/server.py", line 4, in <module>
    from bottle import Bottle, request, abort, static_file, template
ImportError: No module named 'bottle'
```

I'm running Ubuntu 13.10, Python 3.3.2+ and just installed texlive and the requirements.txt. 

I'd appreciate any tips where I'm going horribly wrong very much. Thanks :)

**Comment by JDevlieghere** [comment]
Hi Kilian,

Since bottle supports both Python 2 and 3, I'm guessing pip installed the wrong version. I've had some trouble figuring this out myself. 

As a temporary solution, you can just put the [bottle.py](http://bottlepy.org/bottle.py) module in the intexration folder. The preferable way to fix this though is installing the requirements using **python3-pip** which will automatically select the right version.

Let me know if this solved your problem! 

EDIT: Although this probably is not the cause of your problem, the command `python3 -m intexration -host localhost -port 8000` is outdated as of the last version. I apparently forgot to update the installation documentation, sorry about that. [This is now the correct way to do so.](https://github.com/JDevlieghere/InTeXration/blob/develop/docs/config.md)

**Comment by kiliankoe** [comment]
Thanks, manually plugging bottle.py in there fixed that issue. Well, at least that one. Now I feel like even more of an idiot because it seems to be going on :(

Running `python3 -m intexration config --host localhost` now brings me: 

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1519, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./intexration.py", line 5, in <module>
    from intexration.server import Server, RequestHandler
  File "./intexration.py", line 5, in <module>
    from intexration.server import Server, RequestHandler
ImportError: No module named 'intexration.server'; intexration is not a package
```

**Comment by JDevlieghere** [comment]
No reason to feel like an idiot! If my documentation isn't clear enough, then that's all my fault! ;-)  

Quick question: you did run `python3 setup.py install` right? I'm assuming you are starting the application from withing the root of this repository, try starting the application from a different folder. If this doesn't work, the package probably isn't correctly installed. 

I'll set up a virtual machine with Ubuntu 13.10 in the meantime. Hopefully I can reproduce your problem.

EDIT: Alright, I found some problems related to being root or not. In addition I'm starting to dislike the package_data approach I'm currently following. I will address these issues right away, update the documentation and release a new version. I'll also make sure it's tested on my clean install of Ubuntu server!

**Comment by JDevlieghere** [comment]
I've just released the new version, as promised. Don't forget to pull and have a look at the updated installation and configuration documents, there quite a lot that changed. Let's hope this version solves your problem!

**Comment by kiliankoe** [comment]
Thank you for the extensive help! Looks like everything seems to be working as it should now, this is awesome stuff! :)
