### ISSUE TITLE
Using API keys

### ISSUE THREAD

**Issue by kiliankoe** [JDevlieghere/InTeXration#6]
Hey again ;)

I just ran into an issue when trying to add an API key, I'm guessing the syntax has changed regarding this.

The docs state to use 
`python3 -m intexration api -add 0F304A9A-997A-4207-A1BF-3C74A009F5A0`

This however just starts the server as usual (same goes for all other api commands like list). When GitHub calls the webhook InTeXration throws the corresponding error and logically nothing happens.
`[WARNING] Unauthorized: API key invalid.`

Any ideas?

Thank you very much in advance! :)

**Comment by JDevlieghere** [comment]
I changed the implementation with the previous release but once again forgot to update the documentation before merging with the master branch. Here's a link to the API section on the develop branch: https://github.com/JDevlieghere/InTeXration/blob/develop/docs/config.md#api-keys

As mentioned there, API keys are now stored in a file `/home/intexration/data/api_keys.cvs`. Just add one key per line. You can use anything you like, but GUIDs are recommended.

**Comment by kiliankoe** [comment]
Ah, thanks for the update! I guess I could've checked the develop branch, will do so in the future!
